### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by ohnosee** [Adobe-Experience-Cloud/analytics-1.4-apis#1]
Despite following the POSTMAN guide to the letter I always get an error back. I have the same issue when using other WSSE authentication libraries with these endpoints

```
{
    "error": "Bad Request",
    "error_description": "Invalid created timestamp (''). Values should be in ISO-8601 format",
    "error_uri": null
}
```
I've inspected the header and the created timestamp is the same format as that used by the API Explorer.

**Comment by mike2184** [comment]
What does the Created timestamp look like in your x-wsse header? Here is an example of what my x-wsse header looks like when I make a request that works (PasswordDigest and Nonce omitted):
```
x-wsse:"UsernameToken Username="michrich:OBU Eng SC", PasswordDigest="************", Nonce="*************", Created="2018-05-14T15:56:54.877Z", Algorithm="SHA256""
```

**Comment by ohnosee** [comment]
Using pywsse my X-WSSE header looks like the following:
```
'X-WSSE': 'Username="User:Company", PasswordDigest="************", Nonce="**********", Created="2018-05-14T16:18:07Z"'`
```
I can't get Postman to even send!

**Comment by mike2184** [comment]
What error are you getting when you try to send the request? You can see the Postman Console by going to View -> Show Postman Console

**Comment by ohnosee** [comment]
I'm not on windows or mac machine (on Chromebook) so using the Chrome App - is the console available there? I don't get the impression that the pre-request script is running as it doesn't seem to be populating the header key

**Comment by ohnosee** [comment]
Ah - it was be being a complete Postman newb - I needed to create an environment for the project and add x-wsse as a environmental variable. Got a valid response now!

**Comment by mike2184** [comment]
@ohnosee - I just realized the guide did not include instructions to setup an environment. I've updated the guide. Thanks!

**Comment by mike2184** [comment]
@alv1234 - I added a step to the doc about selecting the environment. Thanks!
