### ISSUE TITLE
Swagger link is broken

### ISSUE THREAD

**Issue by michaelwexler** [Adobe-Experience-Cloud/analytics-1.4-apis#8]
The Swagger link in readme/front page is formatted incorrectly, such that the resulting page results in a CORS block.  

Fetch errorFailed to fetch https://api.omniture.com/admin/1.4/rest/public.json
Fetch errorPossible cross-origin (CORS) issue? The URL origin (https://api.omniture.com) does not match the page (https://adobe-experience-cloud.github.io). Check the server returns the correct 'Access-Control-Allow-*' headers.

**Comment by mike2184** [comment]
This issue is resolved now.

**Comment by michaelwexler** [comment]
Awesome.  Much better, thank you.
